#!/bin/bash
echo "1 - Removing tmp files..."
rm -rf dist
echo "2 - Creating tmp folder..."
mkdir dist
echo "4 - Building findfval.asm..."
nasm findfval.asm -f elf32 -o dist/findfval.o
echo "5 - Buildint findsval.asm..."
nasm findsval.asm -f elf32 -o dist/findsval.o
echo "5 - Linding main.o, findroots.o..."
g++ main.cpp dist/findsval.o dist/findfval.o -m32 -o a.out
echo "6 - Deleting tmp files..."
rm -rf dist 
echo "Successfully Built."

